-- M4 · 0008_seed_foods_br.sql
-- Brazilian food seed from TACO (Tabela Brasileira de Composição de Alimentos,
-- NEPA/UNICAMP, 4th ed.), values per 100 g. Shared read-only seed (is_seed = true).
-- Source data: github.com/raulfdm/taco-api (references/csv).
-- Branded/packaged BR products can be layered later from Open Food Facts (ODbL).

insert into public.foods (name, kcal_per_100, protein_per_100, is_seed) values
  ('Abacate, cru', 96, 1.2, true),
  ('Abacaxi, cru', 48, 0.9, true),
  ('Abobrinha, italiana, cozida', 15, 1.1, true),
  ('Abobrinha, italiana, crua', 19, 1.1, true),
  ('Abóbora, cabotian, cozida', 48, 1.4, true),
  ('Abóbora, cabotian, crua', 39, 1.7, true),
  ('Acelga, crua', 21, 1.4, true),
  ('Acerola, crua', 33, 0.9, true),
  ('Agrião, cru', 17, 2.7, true),
  ('Alface, americana, crua', 9, 0.6, true),
  ('Alface, crespa, crua', 11, 1.3, true),
  ('Alho, cru', 113, 7.0, true),
  ('Ameixa, crua', 53, 0.8, true),
  ('Apresuntado', 129, 13.5, true),
  ('Arroz, integral, cozido', 124, 2.6, true),
  ('Arroz, integral, cru', 360, 7.3, true),
  ('Arroz, tipo 1, cozido', 128, 2.5, true),
  ('Arroz, tipo 1, cru', 358, 7.2, true),
  ('Arroz, tipo 2, cozido', 130, 2.6, true),
  ('Arroz, tipo 2, cru', 358, 7.2, true),
  ('Atum, conserva em óleo', 166, 26.2, true),
  ('Atum, fresco, cru', 118, 25.7, true),
  ('Aveia, flocos, crua', 394, 13.9, true),
  ('Bacalhau, salgado, cru', 136, 29.0, true),
  ('Banana, da terra, crua', 128, 1.4, true),
  ('Banana, maçã, crua', 87, 1.8, true),
  ('Banana, nanica, crua', 92, 1.4, true),
  ('Banana, prata, crua', 98, 1.3, true),
  ('Batata, baroa, cozida', 80, 0.9, true),
  ('Batata, doce, cozida', 77, 0.6, true),
  ('Batata, doce, crua', 118, 1.3, true),
  ('Batata, inglesa, cozida', 52, 1.2, true),
  ('Batata, inglesa, crua', 64, 1.8, true),
  ('Batata, inglesa, frita', 267, 5.0, true),
  ('Berinjela, cozida', 19, 0.7, true),
  ('Berinjela, crua', 20, 1.2, true),
  ('Beterraba, cozida', 32, 1.3, true),
  ('Beterraba, crua', 49, 1.9, true),
  ('Biscoito, doce, maisena', 443, 8.1, true),
  ('Biscoito, doce, recheado com chocolate', 472, 6.4, true),
  ('Biscoito, doce, recheado com morango', 471, 5.7, true),
  ('Biscoito, salgado, cream cracker', 432, 10.1, true),
  ('Bolo, pronto, chocolate', 410, 6.2, true),
  ('Brócolis, cozido', 25, 2.1, true),
  ('Brócolis, cru', 25, 3.6, true),
  ('Caju, cru', 43, 1.0, true),
  ('Camarão, Rio Grande, grande, cozido', 90, 19.0, true),
  ('Camarão, Rio Grande, grande, cru', 47, 10.0, true),
  ('Canjica, branca, crua', 358, 7.2, true),
  ('Caqui, chocolate, cru', 71, 0.4, true),
  ('Carambola, crua', 46, 0.9, true),
  ('Carne, bovina, acém, moído, cozido', 212, 26.7, true),
  ('Carne, bovina, acém, moído, cru', 137, 19.4, true),
  ('Carne, bovina, charque, cozido', 263, 36.4, true),
  ('Carne, bovina, contra-filé, com gordura, grelhado', 278, 32.4, true),
  ('Carne, bovina, contra-filé, sem gordura, grelhado', 194, 35.9, true),
  ('Carne, bovina, contra-filé, à milanesa', 352, 20.6, true),
  ('Carne, bovina, costela, assada', 373, 28.8, true),
  ('Carne, bovina, coxão mole, sem gordura, cozido', 219, 32.4, true),
  ('Carne, bovina, filé mingnon, sem gordura, cru', 143, 21.6, true),
  ('Carne, bovina, filé mingnon, sem gordura, grelhado', 220, 32.8, true),
  ('Carne, bovina, fígado, cru', 141, 20.7, true),
  ('Carne, bovina, fígado, grelhado', 225, 29.9, true),
  ('Carne, bovina, lagarto, cozido', 222, 32.9, true),
  ('Carne, bovina, maminha, grelhada', 153, 30.7, true),
  ('Carne, bovina, miolo de alcatra, sem gordura, grelhado', 241, 31.9, true),
  ('Carne, bovina, músculo, sem gordura, cru', 142, 21.6, true),
  ('Carne, bovina, patinho, sem gordura, grelhado', 219, 35.9, true),
  ('Carne, bovina, picanha, com gordura, grelhada', 289, 26.4, true),
  ('Carne, bovina, picanha, sem gordura, grelhada', 238, 31.9, true),
  ('Carne, bovina, seca, cozida', 313, 26.9, true),
  ('Cebola, crua', 39, 1.7, true),
  ('Cenoura, cozida', 30, 0.8, true),
  ('Cenoura, crua', 34, 1.3, true),
  ('Cereais, milho, flocos, com sal', 370, 7.3, true),
  ('Cereal matinal, milho', 365, 7.2, true),
  ('Chuchu, cozido', 19, 0.4, true),
  ('Chuchu, cru', 17, 0.7, true),
  ('Couve, manteiga, crua', 27, 2.9, true),
  ('Couve-flor, cozida', 19, 1.2, true),
  ('Couve-flor, crua', 23, 1.9, true),
  ('Coxinha de frango, frita', 283, 9.6, true),
  ('Farinha, de mandioca, crua', 361, 1.6, true),
  ('Farinha, de milho, amarela', 351, 7.2, true),
  ('Farinha, de trigo', 360, 9.8, true),
  ('Figo, cru', 41, 1.0, true),
  ('Goiaba, branca, com casca, crua', 52, 0.9, true),
  ('Goiaba, vermelha, com casca, crua', 54, 1.1, true),
  ('Graviola, crua', 62, 0.8, true),
  ('Jabuticaba, crua', 58, 0.6, true),
  ('Jaca, crua', 88, 1.4, true),
  ('Kiwi, cru', 51, 1.3, true),
  ('Laranja, baía, crua', 45, 1.0, true),
  ('Laranja, pêra, crua', 37, 1.0, true),
  ('Limão, tahiti, cru', 32, 0.9, true),
  ('Macarrão, trigo, cru', 371, 10.0, true),
  ('Mamão, Formosa, cru', 45, 0.8, true),
  ('Mamão, Papaia, cru', 40, 0.5, true),
  ('Mandioca, cozida', 125, 0.6, true),
  ('Mandioca, crua', 151, 1.1, true),
  ('Manga, Haden, crua', 64, 0.4, true),
  ('Manga, Tommy Atkins, crua', 51, 0.9, true),
  ('Manteiga, com sal', 726, 0.4, true),
  ('Manteiga, sem sal', 758, 0.4, true),
  ('Maracujá, cru', 68, 2.0, true),
  ('Maçã, Argentina, com casca, crua', 63, 0.2, true),
  ('Maçã, Fuji, com casca, crua', 56, 0.3, true),
  ('Melancia, crua', 33, 0.9, true),
  ('Melão, cru', 29, 0.7, true),
  ('Merluza, filé, assado', 122, 26.6, true),
  ('Merluza, filé, cru', 89, 16.6, true),
  ('Mexerica, Murcote, crua', 58, 0.9, true),
  ('Milho, fubá, cru', 353, 7.2, true),
  ('Milho, verde, cru', 138, 6.6, true),
  ('Morango, cru', 30, 0.9, true),
  ('Pepino, cru', 10, 0.9, true),
  ('Pescada, filé, cru', 107, 16.7, true),
  ('Pimentão, amarelo, cru', 28, 1.2, true),
  ('Pimentão, verde, cru', 21, 1.1, true),
  ('Pinha, crua', 88, 1.5, true),
  ('Pipoca, com óleo de soja, sem sal', 448, 9.9, true),
  ('Pitanga, crua', 41, 0.9, true),
  ('Pão, aveia, forma', 343, 12.4, true),
  ('Pão, trigo, forma, integral', 253, 9.4, true),
  ('Pão, trigo, francês', 300, 8.0, true),
  ('Pêra, Park, crua', 61, 0.2, true),
  ('Pêssego, Aurora, cru', 36, 0.8, true),
  ('Quiabo, cru', 30, 1.9, true),
  ('Repolho, branco, cru', 17, 0.9, true),
  ('Romã, crua', 56, 0.4, true),
  ('Rúcula, crua', 13, 1.8, true),
  ('Salmão, filé, com pele, fresco, grelhado', 229, 23.9, true),
  ('Salmão, sem pele, fresco, cru', 170, 19.3, true),
  ('Salmão, sem pele, fresco, grelhado', 243, 26.1, true),
  ('Salsa, crua', 33, 3.3, true),
  ('Sardinha, assada', 164, 32.2, true),
  ('Sardinha, conserva em óleo', 285, 15.9, true),
  ('Sardinha, inteira, crua', 114, 21.1, true),
  ('Tangerina, Poncã, crua', 38, 0.8, true),
  ('Tomate, com semente, cru', 15, 1.1, true),
  ('Tomate, salada', 21, 0.8, true),
  ('Torrada, pão francês', 377, 10.5, true),
  ('Uva, Itália, crua', 53, 0.7, true),
  ('Uva, Rubi, crua', 49, 0.6, true),
  ('Vagem, crua', 25, 1.8, true)
on conflict do nothing;
